### ISSUE TITLE
Rhino's Iron Skin doesn't seem to use the extra armor from Health Conversion

### ISSUE THREAD

**Issue by HK47196** [cmd430/Warframe-EHP-Calculator#2] opened 2018-05-23 06:59 UTC
Issue title. Wiki implies they work together, and the ability info screen ingame definitely shows a big absorb increase with health conversion pickups.

**Comment by cmd430** [comment] 2018-05-24 09:34
It seems to be working fine on my end any chance you can do a step by step (with pics too if possible) on how you get this issue?

**Comment by cmd430** [comment] 2018-05-24 09:40
Here is an Imgur Album https://imgur.com/a/O3vas7W showing it on my end (Note the EHP values)

**Comment by cmd430** [comment] 2018-06-02 06:00
am closing this issue, if you can provide steps to reproduce i'll reopen

**Closed as completed by cmd430** 2018-06-02 06:00 UTC
Labels: invalid
