### ISSUE TITLE
Pax Bolt not applying completely

### ISSUE THREAD

**Issue by GlitchMC** [cmd430/Warframe-EHP-Calculator#19] opened 2020-01-09 22:05 UTC
Pax Bolt's 30% Ability Strength bonus correctly gets added to the Power Strength line in the sidebar, but doesn't get applied to abilities that affect EHP such as Wisp's Health mote or Chroma's Elemental Ward.

Elemental Ward
![image](https://user-images.githubusercontent.com/21283974/72108657-1c8a5380-3302-11ea-946c-1de3e9e55da0.png)
![image](https://user-images.githubusercontent.com/21283974/72108669-2318cb00-3302-11ea-8078-f431ce58f72b.png)

Health Mote
![image](https://user-images.githubusercontent.com/21283974/72108699-3166e700-3302-11ea-8a00-4dde1fdff64c.png)

![image](https://user-images.githubusercontent.com/21283974/72108720-37f55e80-3302-11ea-8c03-defe8549a1bc.png)

**Comment by cmd430** [comment] 2020-01-10 10:35
Thanks, I know what the issue is and will push an update hopefully tomorrow when I have time to actually fix it.

If you wanted to know what the issue actually is, its because its setup like the other arcanes so its adding its effect _after_ the mods and abilities are taken into account when it should be added after mods but before abilities

**Comment by GlitchMC** [comment] 2020-01-10 10:43
I figured it was something like that, yeah. 

Not sure how you have things set up, but what I would have done is make the ability strength that gets displayed on the sidebar be used for calculations instead of having a one variable to hold the strength for calculations and one for displaying.

**Comment by cmd430** [comment] 2020-01-10 11:00
The strength displayed is from the variable used in the calculations its just when the str from the arcane is added the other calculations for the abilities have already been done 

The armor arcanes work like this because they are added after everything else and I accidentally did the same for the pax bolt without really thinking about it

**Comment by GlitchMC** [comment] 2020-01-10 11:31
Ah, I see, okay. I've done that before lol.

**Comment by cmd430** [comment] 2020-01-11 05:47
closed by 42c7c5b

**Closed as completed by cmd430** 2020-01-11 05:47 UTC
Labels: bug, completed, confirmed
